default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>

development:
  <<: *default
  database: promo_development

test:
  <<: *default
  database: promo_test

production:
  primary: &primary_production
    <<: *default
    database: promo_production
    username: promo
    password: <%= ENV["PROMO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: promo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: promo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: promo_production_cable
    migrations_paths: db/cable_migrate
